service: karaoke-backend-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - dev

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: greetings/hello
          method: post
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          path: greetings/goodbye
          method: post
